pull_request_rules:
  - name: Automatic merge
    conditions:
        - author=github-actions[bot]
        - title=Update flake.lock
    actions:
      merge:
        method: merge
      delete_head_branch: